[general]
import = ["catppuccin-mocha.toml"]
working_directory = "\\\\wsl.localhost\\Ubuntu-24.04\\home\\thitiwut"

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[terminal]
shell = "wsl.exe"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size = 13

[window]
dimensions = { columns = 120, lines = 30 }

