theme = "solarized_light"

[editor]
line-number = "relative"
true-color = true
color-modes = true
auto-pairs = false
shell = ["bash", "-c"]
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[keys.select]
# Include the last line for "ge".
"g" = { "e" = "goto_file_end" }
